import type { Metadata } from "next";
import { Space_Mono, Inter } from "next/font/google";
import { GeistSans } from "geist/font/sans";
import SmoothScroll from "@/lib/scroll/SmoothScroll";
import CrtPowerOn from "@/components/site/CrtPowerOn";
import CustomCursor from "@/components/site/CustomCursor";
import SoundToggle from "@/components/site/SoundToggle";
import WhatsAppButton from "@/components/site/WhatsAppButton";
import "./globals.css";

// Display: big statements, the shatter-revealed wordmark. Geist (Vercel,
// SIL Open Font License — fully open, no commercial-license question at
// all) instead of Bricolage Grotesque, which became the default "give it
// personality" font of nearly every AI site generator through 2024-2025.
const geistSans = GeistSans;

// Kicker/mono: section eyebrows, stats, the CRT/glitch register. Doing the
// same positioning work Azeret Mono does on notionlabs.in — technical,
// internet-native — without literally reusing their font.
const spaceMono = Space_Mono({
  variable: "--font-space-mono",
  weight: ["400", "700"],
  subsets: ["latin"],
});

// Body: stays out of the way.
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const SITE_URL = "https://iorastudio.vercel.app";
const SITE_TITLE = "ïora — AI Ads & Websites";
const SITE_DESCRIPTION =
  "iora is an AI ads and websites studio for brands that refuse to be scrolled past.";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: SITE_TITLE,
  description: SITE_DESCRIPTION,
  // The actual share-card image is generated by app/opengraph-image.tsx
  // (Next.js's own file convention — picked up automatically, no need to
  // reference it here). openGraph/twitter below just fill in the
  // surrounding title/description/siteName that convention doesn't cover,
  // and give Twitter/X's own crawler (which some platforms fall back to
  // if og: tags alone are ambiguous) an explicit large-image card type.
  openGraph: {
    title: SITE_TITLE,
    description: SITE_DESCRIPTION,
    url: SITE_URL,
    siteName: "iora",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: SITE_TITLE,
    description: SITE_DESCRIPTION,
  },
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${spaceMono.variable} ${inter.variable} h-full antialiased`}
    >
      <head>
        {/* Runs synchronously as the browser parses <head>, before Lenis,
            GSAP, or any React effect ever gets a chance to run — the
            earliest possible point. This is a one-shot cinematic scroll
            story (CRT power-on, marble drops, section-entrance
            animations), not a content page anyone expects to resume
            mid-scroll: every one of those entrance animations was built
            assuming a fresh start from scrollY 0, and none of them
            re-derive "what should my state already be, given I'm
            mounting midway down the page" — a browser-restored scroll
            position on refresh left them permanently out of sync with
            where they visually were (CRT noise replaying, the Impact
            marble vanishing, reported directly). `scrollRestoration =
            "manual"` stops the browser from doing that restoration at
            all; the immediate `scrollTo` covers the current load too,
            not just future ones. next/script's variants are all deferred
            (afterInteractive at the earliest) — too late here, since the
            browser's own restoration has often already happened by then. */}
        <script
          dangerouslySetInnerHTML={{
            __html: `if("scrollRestoration" in history){history.scrollRestoration="manual";}window.scrollTo(0,0);`,
          }}
        />
      </head>
      {/* Plain block flow, not flex — a flex ancestor of a GSAP-pinned
          section corrupts the pin-spacer's height calculation (confirmed:
          isolated to the flex container alone, reproducible independent of
          Lenis/StrictMode/overflow-hidden/absolute children). Full-height
          sections stack correctly with ordinary block layout; flex was
          never actually needed here. */}
      {/* suppressHydrationWarning here — NOT masking a real mismatch,
          scoped to only this one element (React doesn't propagate it to
          children). The ColorZilla browser extension injects a
          `cz-shortcut-listen="true"` attribute onto <body> before React
          hydrates, which the server obviously never rendered — one of
          Next.js's own explicitly-documented false-positive causes
          ("a browser extension installed which messes with the HTML
          before React loaded"). Real mobile Safari sessions don't have
          this extension; it only shows up testing via desktop Chrome's
          mobile emulation with ColorZilla installed. */}
      <body className="min-h-full bg-ink text-chalk" suppressHydrationWarning>
        <CrtPowerOn />
        <CustomCursor />
        <SoundToggle />
        <WhatsAppButton />
        <SmoothScroll>{children}</SmoothScroll>
      </body>
    </html>
  );
}
