import type { Metadata } from "next";
import { Anton, Instrument_Sans } from "next/font/google";
import { GeistMono } from "geist/font/mono";
import SmoothScroll from "@/lib/scroll/SmoothScroll";
import CrtPowerOn from "@/components/site/CrtPowerOn";
import CustomCursor from "@/components/site/CustomCursor";
import SoundToggle from "@/components/site/SoundToggle";
import WhatsAppButton from "@/components/site/WhatsAppButton";
import VideoDebugOverlay from "@/components/site/VideoDebugOverlay";
import "./globals.css";

// TWO faces total, doing every job on the site — down from three (Geist
// display / Inter body / Space Mono kicker). The previous trio's real
// problem wasn't any individual choice, it was that Geist and Inter are
// both clean neo-grotesks: two fonts spending their character budget on
// nearly the same voice, so the site read as generically well-set rather
// than authored. Collapsing display+body onto ONE face and letting the
// mono carry all the interface/label work gives a single typographic
// fingerprint, with hierarchy coming from proportion and weight instead
// of from family-switching.
//
// Instrument Sans (SIL Open Font License) for both display and body — a
// variable face with slightly more editorial personality in its
// letterforms than Geist/Inter while staying quiet enough to set long
// copy. Loaded as a variable font (no explicit `weight`) so the full
// 400-700 axis is available: the display sizes lean on 600, section
// headings sit just under it, and body stays at 400, which is the kind
// of fine-grained weight separation a static two-weight setup can't do.
const instrumentSans = Instrument_Sans({
  variable: "--font-instrument-sans",
  subsets: ["latin"],
});

// Kicker/mono: section eyebrows ("[ THE PROBLEM ]"), nav labels, the
// numbered ecosystem card titles, the CRT/glitch register. Geist Mono
// rather than Space Mono — Space Mono's quirkier letterforms read as a
// third distinct voice, whereas Geist Mono is a true companion to a
// neutral sans, so the mono treatment becomes a recognisable interface
// language across the site instead of decorative small tracked type.
// Already vendored (the `geist` package is a dependency), so this costs
// no extra network request beyond the subset actually used.
const geistMono = GeistMono;

// A THIRD face, used in exactly one place: the boot screen's loading
// words (see CrtPowerOn). Deliberately not a general-purpose addition —
// the two-face discipline above still governs the rest of the site, and
// nothing else should reach for this.
//
// It exists because the loader's whole mechanic is a fill rising inside
// hollow letterforms, and that needs glyphs with real enclosed area to
// fill. Instrument Sans at 700 was the first attempt and was too light and
// too wide-spaced for it to read; a heavy condensed grotesque packs far
// more ink per character, so each letter becomes a tall solid shape the
// level can visibly climb.
//
// Anton, not Druk Condensed. Druk (Commercial Type) is the face the
// reference site uses, and it is a paid licence — its font files can't be
// copied out of someone else's site into this project. Anton (SIL Open
// Font License) is the closest free equivalent: same heavy-condensed
// grotesque genre, same "single very bold weight" character. If a Druk
// licence is ever bought, swapping it in means changing only
// `--font-condensed` in globals.css — nothing in the component knows the
// family name.
const anton = Anton({
  variable: "--font-anton",
  subsets: ["latin"],
  weight: "400", // Anton ships one weight; it is already display-black.
});

const SITE_URL = "https://iorastudio.vercel.app";
const SITE_TITLE = "ïora — Creative Growth Ecosystems";
const SITE_DESCRIPTION =
  "Custom growth ecosystems connecting brand, cinematic campaigns, websites and integrations to generate leads, improve conversion and build repeat business.";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: SITE_TITLE,
  description: SITE_DESCRIPTION,
  // The actual share-card image is generated by app/opengraph-image.tsx
  // (Next.js's own file convention — picked up automatically, no need to
  // reference it here). openGraph/twitter below just fill in the
  // surrounding title/description/siteName that convention doesn't cover,
  // and give Twitter/X's own crawler (which some platforms fall back to
  // if og: tags alone are ambiguous) an explicit large-image card type.
  openGraph: {
    title: SITE_TITLE,
    description: SITE_DESCRIPTION,
    url: SITE_URL,
    siteName: "iora",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: SITE_TITLE,
    description: SITE_DESCRIPTION,
  },
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${instrumentSans.variable} ${geistMono.variable} ${anton.variable} h-full antialiased`}
    >
      <head>
        {/* Runs synchronously as the browser parses <head>, before Lenis,
            GSAP, or any React effect ever gets a chance to run — the
            earliest possible point. This is a one-shot cinematic scroll
            story (CRT power-on, marble drops, section-entrance
            animations), not a content page anyone expects to resume
            mid-scroll: every one of those entrance animations was built
            assuming a fresh start from scrollY 0, and none of them
            re-derive "what should my state already be, given I'm
            mounting midway down the page" — a browser-restored scroll
            position on refresh left them permanently out of sync with
            where they visually were (CRT noise replaying, the Impact
            marble vanishing, reported directly). `scrollRestoration =
            "manual"` stops the browser from doing that restoration at
            all; the immediate `scrollTo` covers the current load too,
            not just future ones. next/script's variants are all deferred
            (afterInteractive at the earliest) — too late here, since the
            browser's own restoration has often already happened by then. */}
        <script
          dangerouslySetInnerHTML={{
            __html: `if("scrollRestoration" in history){history.scrollRestoration="manual";}window.scrollTo(0,0);`,
          }}
        />
      </head>
      {/* Plain block flow, not flex — a flex ancestor of a GSAP-pinned
          section corrupts the pin-spacer's height calculation (confirmed:
          isolated to the flex container alone, reproducible independent of
          Lenis/StrictMode/overflow-hidden/absolute children). Full-height
          sections stack correctly with ordinary block layout; flex was
          never actually needed here. */}
      {/* suppressHydrationWarning here — NOT masking a real mismatch,
          scoped to only this one element (React doesn't propagate it to
          children). The ColorZilla browser extension injects a
          `cz-shortcut-listen="true"` attribute onto <body> before React
          hydrates, which the server obviously never rendered — one of
          Next.js's own explicitly-documented false-positive causes
          ("a browser extension installed which messes with the HTML
          before React loaded"). Real mobile Safari sessions don't have
          this extension; it only shows up testing via desktop Chrome's
          mobile emulation with ColorZilla installed. */}
      <body className="min-h-full bg-ink text-chalk" suppressHydrationWarning>
        <CrtPowerOn />
        <CustomCursor />
        <SoundToggle />
        <WhatsAppButton />
        {/* Renders nothing at all unless the URL carries ?debug=video —
            see the component's own doc comment. Kept mounted here rather
            than behind a route so it can observe the real homepage in its
            real state on a real device. */}
        <VideoDebugOverlay />
        <SmoothScroll>{children}</SmoothScroll>
      </body>
    </html>
  );
}
